import { ClerkProvider } from '@clerk/nextjs';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ThemeProvider } from '@/providers/theme-provider';
import Container from '@/components/Container';
import Navbar from '@/components/Navbar';
import StateProvider from '@/providers/state-provider';
import ToastProvider from '@/providers/toast-provide';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang='en' suppressHydrationWarning>
        <body className={inter.className}>
          <ThemeProvider attribute='class'>
            <StateProvider>
              <Container>
                <Navbar />
                {children}
              </Container>
              <ToastProvider />
            </StateProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
